import { User, Ticket, Comment, SLAConfig, DashboardStats } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    email: "admin@empresa.com",
    name: "Admin Sistema",
    role: "admin",
    department: "TI",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "u2",
    email: "suporte@empresa.com",
    name: "Carlos Suporte",
    role: "support",
    department: "TI",
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "u3",
    email: "ana@empresa.com",
    name: "Ana Souza",
    role: "support",
    department: "TI",
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "u4",
    email: "joao@empresa.com",
    name: "João Silva",
    role: "user",
    department: "Financeiro",
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "u5",
    email: "maria@empresa.com",
    name: "Maria Oliveira",
    role: "user",
    department: "RH",
    created_at: "2024-02-05T00:00:00Z",
  },
  {
    id: "u6",
    email: "pedro@empresa.com",
    name: "Pedro Costa",
    role: "user",
    department: "Comercial",
    created_at: "2024-02-10T00:00:00Z",
  },
];

const now = new Date();
const h = (hours: number) => new Date(now.getTime() - hours * 3600000).toISOString();

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "c1",
    ticket_id: "t1",
    author_id: "u2",
    author: MOCK_USERS[1],
    content: "Analisando o problema. Vou verificar as configurações de rede.",
    is_internal: false,
    created_at: h(3),
  },
  {
    id: "c2",
    ticket_id: "t1",
    author_id: "u2",
    author: MOCK_USERS[1],
    content: "IP duplicado na rede. Corrigindo...",
    is_internal: true,
    created_at: h(2),
  },
  {
    id: "c3",
    ticket_id: "t2",
    author_id: "u3",
    author: MOCK_USERS[2],
    content: "Resetando a senha agora. Você receberá um email em instantes.",
    is_internal: false,
    created_at: h(1),
  },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: "t1",
    ticket_number: "TKT-001",
    title: "Computador sem acesso à internet",
    description: "Meu computador da estação de trabalho perdeu o acesso à internet depois da atualização do Windows de ontem à tarde. Outros computadores da sala estão funcionando normalmente.",
    status: "in_progress",
    priority: "high",
    category: "network",
    created_by: "u4",
    assigned_to: "u2",
    created_by_user: MOCK_USERS[3],
    assigned_to_user: MOCK_USERS[1],
    sla_deadline: h(1), // criado há 6h, SLA de 8h venceu há 1h -> violado
    sla_breached: true,
    created_at: h(6),
    updated_at: h(2),
    comments: MOCK_COMMENTS.filter(c => c.ticket_id === "t1"),
  },
  {
    id: "t2",
    ticket_number: "TKT-002",
    title: "Senha do sistema ERP bloqueada",
    description: "Após 3 tentativas erradas, minha senha do ERP foi bloqueada. Preciso de acesso urgente para fechar o faturamento do mês.",
    status: "in_progress",
    priority: "critical",
    category: "access",
    created_by: "u5",
    assigned_to: "u3",
    created_by_user: MOCK_USERS[4],
    assigned_to_user: MOCK_USERS[2],
    sla_deadline: h(-2), // criado há 2h, SLA crítico de 4h -> faltam 2h
    sla_breached: false,
    created_at: h(2),
    updated_at: h(1),
    comments: MOCK_COMMENTS.filter(c => c.ticket_id === "t2"),
  },
  {
    id: "t3",
    ticket_number: "TKT-003",
    title: "Impressora do departamento comercial offline",
    description: "A impressora HP do setor comercial aparece offline para todos os computadores. Já tentei reiniciar mas não adiantou.",
    status: "open",
    priority: "medium",
    category: "hardware",
    created_by: "u6",
    created_by_user: MOCK_USERS[5],
    sla_deadline: h(-20), // criado há 4h, SLA médio de 24h -> faltam 20h (seguro)
    sla_breached: false,
    created_at: h(4),
    updated_at: h(1),
    comments: [],
  },
  {
    id: "t8",
    ticket_number: "TKT-008",
    title: "Notebook não carrega a bateria",
    description: "O notebook Dell do setor de RH não está carregando. A luz do carregador acende mas a bateria não sobe do nível atual.",
    status: "open",
    priority: "high",
    category: "hardware",
    created_by: "u5",
    created_by_user: MOCK_USERS[4],
    sla_deadline: h(-0.5),
    sla_breached: false,
    created_at: h(7.5),
    updated_at: h(7.5),
    comments: [],
  },
  {
    id: "t4",
    ticket_number: "TKT-004",
    title: "Excel travando ao abrir planilhas grandes",
    description: "O Excel trava e fecha sozinho ao tentar abrir planilhas com mais de 50MB. O problema começou após a última atualização do Office.",
    status: "open",
    priority: "medium",
    category: "software",
    created_by: "u4",
    created_by_user: MOCK_USERS[3],
    sla_deadline: h(-20), // criado há 4h, SLA médio 24h -> faltam 20h
    sla_breached: false,
    created_at: h(4),
    updated_at: h(4),
    comments: [],
  },
  {
    id: "t5",
    ticket_number: "TKT-005",
    title: "Solicitação de novo monitor",
    description: "Meu monitor apresenta linhas horizontais na tela. Preciso de troca para continuar trabalhando.",
    status: "waiting_user",
    priority: "low",
    category: "hardware",
    created_by: "u5",
    assigned_to: "u2",
    created_by_user: MOCK_USERS[4],
    assigned_to_user: MOCK_USERS[1],
    sla_deadline: h(-48),
    sla_breached: false,
    created_at: h(48),
    updated_at: h(24),
    comments: [],
  },
  {
    id: "t6",
    ticket_number: "TKT-006",
    title: "VPN não conecta de casa",
    description: "Desde ontem não consigo me conectar à VPN da empresa para trabalhar remotamente. Erro: 'Authentication failed'.",
    status: "resolved",
    priority: "high",
    category: "network",
    created_by: "u6",
    assigned_to: "u3",
    created_by_user: MOCK_USERS[5],
    assigned_to_user: MOCK_USERS[2],
    resolved_at: h(2),
    created_at: h(10),
    updated_at: h(2),
    comments: [],
  },
  {
    id: "t7",
    ticket_number: "TKT-007",
    title: "Acesso ao Google Drive corporativo negado",
    description: "Recebi mensagem de permissão negada ao tentar acessar a pasta compartilhada do projeto X no Google Drive.",
    status: "closed",
    priority: "low",
    category: "access",
    created_by: "u4",
    assigned_to: "u3",
    created_by_user: MOCK_USERS[3],
    assigned_to_user: MOCK_USERS[2],
    resolved_at: h(26),
    closed_at: h(24),
    created_at: h(30),
    updated_at: h(24),
    comments: [],
  },
];

export const MOCK_SLA: SLAConfig[] = [
  { id: "s1", priority: "low", response_hours: 24, resolution_hours: 72 },
  { id: "s2", priority: "medium", response_hours: 8, resolution_hours: 24 },
  { id: "s3", priority: "high", response_hours: 4, resolution_hours: 8 },
  { id: "s4", priority: "critical", response_hours: 1, resolution_hours: 4 },
];

export const MOCK_STATS: DashboardStats = {
  total_open: 2,
  total_in_progress: 2,
  total_resolved_today: 3,
  total_sla_breached: 1,
  avg_resolution_hours: 5.3,
  tickets_by_category: [
    { category: "Rede", count: 2 },
    { category: "Hardware", count: 2 },
    { category: "Acesso", count: 2 },
    { category: "Software", count: 1 },
  ],
  tickets_by_priority: [
    { priority: "Crítica", count: 1 },
    { priority: "Alta", count: 2 },
    { priority: "Média", count: 2 },
    { priority: "Baixa", count: 2 },
  ],
  resolution_trend: [
    { date: "06/06", count: 2 },
    { date: "07/06", count: 4 },
    { date: "08/06", count: 1 },
    { date: "09/06", count: 5 },
    { date: "10/06", count: 3 },
    { date: "11/06", count: 6 },
    { date: "12/06", count: 3 },
  ],
};

// Current logged in user (simulating auth)
export const CURRENT_USER = MOCK_USERS[0]; // admin by default
